### ISSUE TITLE
How To Run On Localhost on windows 11

### ISSUE THREAD

**Issue by dadevguy** [Ghostload74/Heliactyl-12#1]
please explain it in README.md

**Comment by dave9123** [comment]
Type the following in your command prompt.

`npm install`
`node index.js`

**Make sure you set up the settings.json before doing those**

**Comment by dadevguy** [comment]
what redirect url i have to add in discord auth

**Comment by Ghostload74** [comment]
Your Dashboard URL 
somehting like 
https://yourdomain.com/callback

**Comment by dadevguy** [comment]
Ohk i am running on loclhost so localhost:8000/callback?

**Comment by Ghostload74** [comment]
no you need to use your domain.

**Comment by dave9123** [comment]
But if you run it in localhost for yourself (IP log in won't work as it goes to a direct domain), you can make it to 127.0.0.1:(port)/callback

**Comment by dadevguy** [comment]
OK

**Comment by dave9123** [comment]
Close it if your issue is/was solved lol

**Comment by dadevguy** [comment]
ok lol
